name: "Previous PR in the stack is merged"
description: "Prevent merging of stacked PRs when previous PR is not yet merged"
author: "Adam Hupp"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  stack-branch-prefixes:
    description: Comma separated array of branch prefixes that indicate a stacked PR
    required: false
    default: stack/
