name: "Stacked PR merge check"
description: "Prevent merging of stacked PRs when ancestors are not merged"
author: "Adam Hupp"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  stack-branch-prefix:
    description: Array of branch prefixes that indicate a stacked PR
    required: false
    default: ["gh/"]
